DROP DATAVERSE TinyBenchmark IF EXISTS;
CREATE DATAVERSE TinyBenchmark;
USE TinyBenchmark;

CREATE TYPE RoadNetworkType AS {
	id: UUID,
	g: geometry,
	attr0: string?,
	attr1: string?,
	attr2: string?,
	attr3: string?,
	attr4: string?
};

CREATE TYPE BuildingsType AS {
	id: UUID,
	g: geometry,
	attr0: string?,
	attr1: string?
};

CREATE TYPE AllNodesType AS {
	id: UUID,
	g: geometry,
	attr0: string?,
	attr1: string?
};

CREATE DATASET RoadNetwork (RoadNetworkType) PRIMARY KEY id AUTOGENERATED;
CREATE DATASET Buildings (BuildingsType) PRIMARY KEY id AUTOGENERATED;
CREATE DATASET AllNodes (AllNodesType) PRIMARY KEY id AUTOGENERATED;
CREATE DATASET TempAllNodes (AllNodesType) PRIMARY KEY id AUTOGENERATED;
CREATE DATASET TempRoadNetwork (RoadNetworkType) PRIMARY KEY id AUTOGENERATED;