CREATE TYPE UrbanAreasType AS {
 id: UUID,
 g: geometry?,
 scalerank: int?,
 featurecla: string?,
 area_sqkm: double?,
 min_zoom: double?
};

CREATE DATASET UrbanAreas (UrbanAreasType) PRIMARY KEY id AUTOGENERATED;

LOAD DATASET UrbanAreas using localfs
(('path'='127.0.0.1:///Users/andretran/Documents/Projects/AsterixDB/bigDatasets/NE_urban_areas.json'),
('format'='adm'));
